Makefile: Add profiling support, work around DocBook 5 issues, etc.
+ Add support for profiling based on lifecycle state of the release
+ Avoid round-tripping en-US through the l10n machinery (which at best
  introduces no changes, at worst introduces old translations and other
  problems)
+ In po-selector, always let en_GB through, as it does not need too many
  changes

diff --git a/po/po-selector b/po/po-selector
--- a/po/po-selector
+++ b/po/po-selector
@@ -16,16 +16,19 @@
 NEW_AGE=31
 
 # Criterion for po files to qualify.
-# Implemented vaules: at_least, mandatory_at_least
+# Implemented values: at_least, mandatory_at_least
 CRITERION=at_least
 
 # Criterion for po files edited in last n days to qualify.
-# Implemented vaules: at_least, mandatory_at_least
+# Implemented values: at_least, mandatory_at_least
 CRITERION_NEW=at_least
 
 # Number of strings that must be translated to qualify. Only for at_least.
 # value in percents
 AT_LEAST=60
+
+# Anything based on BASELANG is excluded from the AT_LEAST check
+BASELANG='en'
 
 # Number of strings that must be translated in files edited in last n days to qualify. Only for at_least.
 # value in percents
@@ -60,7 +63,7 @@ function get_po_age() {
   if test -z "$DATE" ; then
     echo 0
   else
-    eval echo $(( ( $CURRENT_date_s - $(if ! date -d "$DATE" +%s ; then echo 0 ; fi) ) / 86440 ))
+    eval echo $(( ( $CURRENT_date_s - $(if ! date -d "$DATE" +%s 2> /dev/null; then echo 0 ; fi) ) / 86440 ))
   fi
   rm -f $1.po-date
 }
@@ -71,9 +74,9 @@ cd `dirname $0`
 for PO in *.po ; do
   echo -n >&2 "$PO: "
   AGE=$(get_po_age "$PO")
-  echo -n >&2 "age $AGE days, "
+  echo -n >&2 "age $AGE days "
   if test $AGE -gt $NEW_AGE ; then
-    echo -n >&2 "applying rule ${CRITERION//_/ } $AT_LEAST% for old files, "
+    echo -n >&2 "(i.e. old), need ${CRITERION//_/ } $AT_LEAST% translated, "
     THRESHOLD=$AT_LEAST
     case $CRITERION in
     at_least )
@@ -84,7 +87,7 @@ for PO in *.po ; do
     ;;
     esac
   else
-    echo -n >&2 "applying rule ${CRITERION_NEW//_/ } $NEW_AT_LEAST% for new files, "
+    echo -n >&2 "(i.e. new), need ${CRITERION_NEW//_/ } $NEW_AT_LEAST% translated, "
     THRESHOLD=$NEW_AT_LEAST
     case $CRITERION_NEW in
     at_least )
@@ -96,12 +99,12 @@ for PO in *.po ; do
     esac
   fi
   if test $PERCENTAGE -ge $THRESHOLD ; then
-    echo >&2 "got $PERCENTAGE%, passed."
+    echo >&2 "got $PERCENTAGE%. [passed]"
+    echo -n " $PO" | sed 's/\.po//'
+  elif test $(echo "$PO" | grep "^$BASELANG[-_]"); then
+    echo >&2 "got $PERCENTAGE%, but language is special. [passed]"
     echo -n " $PO" | sed 's/\.po//'
   else
-    echo >&2 "got $PERCENTAGE%, too weak."
+    echo >&2 "got $PERCENTAGE%. [failed]"
   fi
 done >LINGUAS
-
-# make sure english is always there
-test -e en.po || echo " en" >> LINGUAS
